### ISSUE TITLE
Wrong flag on dashboard when using Swedish locale

### ISSUE THREAD

**Issue by pnikrat** [prograils/lit#104]
Some languages have their locale codes different from country codes. When using `:sv` locale code in Rails app, FamFam in Lit maps it to Salvador flag instead of a Swedish one.
![zrzut ekranu z 2018-10-08 12-39-31](https://user-images.githubusercontent.com/11310262/46605735-dccf2d80-cafa-11e8-922c-ac46119dfe10.png)
![zrzut ekranu z 2018-10-08 12-54-56](https://user-images.githubusercontent.com/11310262/46605746-e0fb4b00-cafa-11e8-96c8-2d5600f793d9.png)

**Comment by yuhkit** [comment]
Chinese: zh
China: cn

In this condition, following error occurred and I cannot see any pages.

```
The asset "lit/famfamfam_flags/zh.png" is not present in the asset pipeline.
```

**Comment by pnikrat** [comment]
FamFamFam was removed and replaced with proper emoji_flags
