### ISSUE TITLE
status of tests?

### ISSUE THREAD

**Issue by jsharpe-mr** [prograils/lit#117]
What are the status of tests for this gem? It's apparently not as simple as appraisal install && appraisal rake test - I also see no Gemfile for the gem, so bundling the gem deps (like appraisal) isn't currently possible on master. Happy to help cleanup, but want to know what the status is before I dive in.

Thanks!

**Comment by vincentvanbush** [comment]
I think this is what's needed:
```
RAILS_ENV=test appraisal rake db:setup # this might fail at one of the appraisals, but it's fine
appraisal bundle install
appraisal rake test
```
There is no Gemfile right now indeed; we understand that it would be handy for it to just be there, containing the `gemspec` declaration in a standard way.

Build status can be seen at https://travis-ci.org/prograils/lit/branches. The tests are failing at Rails 5.1 because of a known bug in i18n (see #98), they're fine otherwise.

**Comment by jsharpe-mr** [comment]
```RAILS_ENV=test appraisal rake db:setup
>> BUNDLE_GEMFILE=/Users/josh/lit/gemfiles/rails_4.2.gemfile bundle exec rake db:setup
Storage: redis
FATAL:  role "lit" does not exist
/Users/josh/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `rescue in connect'
/Users/josh/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `connect'
/Users/josh/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'

**Comment by jsharpe-mr** [comment]
Eh, guess that's a pg error - got it.

**Comment by jsharpe-mr** [comment]
Yea, so I also get this thing:
```
ppraisal rake test
>> BUNDLE_GEMFILE=/Users/josh/lit/gemfiles/rails_4.2.gemfile bundle exec rake test
Storage: redis

File does not exist: devise
```
...which is coming from this thing:

https://github.com/prograils/lit/blob/master/test/dummy/config/application.rb#L2

My understanding is that line shouldn't really be necessary since it's in the gemfile.  Even if I move that require statement below `Bundler.require` it still bombs out the same way.
