### ISSUE TITLE
Intermittent value for Localization keys in admin

### ISSUE THREAD

**Issue by scottbarrow** [prograils/lit#132]
I am logged into /admin and have a localization key dashboard.groups.programs.items.unfinished_award_entries.description 
the key has 9 languages. 3 of which have values for en, es, fr. 
However when refreshing the page, the french value intermittently blanks out. On inspecting the page the same key id is used for when the value is present and not present.
The site is load balanced over 3 rails servers, however I don't believe load balancing to be the issue here as checking the database on each provides the same record (below)
Do you have any recommendations on how to troubleshoot this further?

```#<Lit::Localization:0x0000000fd6ba50
  id: 74902,
  locale_id: 1,
  localization_key_id: 23829,
  default_value: "Unfinished award entries",
  translated_value: nil,
  is_changed: false,
  created_at: Mon, 01 Apr 2019 20:07:20 UTC +00:00,
  updated_at: Mon, 01 Apr 2019 20:07:20 UTC +00:00>]```

**Comment by mlitwiniuk** [comment]
Hi @scottbarrow,

and what do you have set as `Lit.key_value_engine` (in `config/initializers/lit.rb`)? It should be `redis`

**Comment by scottbarrow** [comment]
Hi,

`Lit.key_value_engine = Rails.env.production? ? 'Redis' : 'hash'`

Thanks

**Comment by scottbarrow** [comment]
Hey, do you have any steps I can take to continue troubleshoot this?

Thanks

**Comment by mlitwiniuk** [comment]
HI @scottbarrow,

Basically whenever you have load balanced app and it's not consistently returning translated value, then most likely there is something wrong with cache store.

Try running (in console) following: `Lit.get_key_value_engine`, it should return something like `> #<Lit::RedisStorage:0x00007f85980c8a80>`. Also - make sure you have Redis configured properly - check here for more details: https://github.com/prograils/lit/blob/master/lib/lit/adapters/redis_storage.rb#L11

**Comment by scottbarrow** [comment]
Thanks, So the server did not have redis installed for some reason, this has now been installed 
`ENV[ENV['REDIS_PROVIDER'] || 'REDIS_URL']` (0.2.6) I get the correct redis ip.

This does resolve the issue with intermittent values.
Thanks @mlitwiniuk
