### ISSUE TITLE
Demo screenshot not working anymore

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [prograils/lit#137]
See https://github.com/prograils/lit/wiki/Screenshots

**Comment by F-3r** [comment]
these links are still broken... any plan to get those images up again anytime?

**Comment by mlitwiniuk** [comment]
@F-3r I'll try to reupload them later today or tomorrow, thanks for raising this.

**Comment by bblimke** [comment]
these would be very useful

**Comment by mlitwiniuk** [comment]
Sorry all, Screenshot page fixed. There is also youtube video describing it's all features: [youtube](https://www.youtube.com/watch?v=_T9Kg05VvLI)

**Comment by bblimke** [comment]
@mlitwiniuk thank you! 👍
