### ISSUE TITLE
Track translation usage

### ISSUE THREAD

**Issue by 3eggert** [prograils/lit#146]
Is it possible to see which translations have been used? 
I have an application which is developed for more than 10 years and there are many translation keys which are not used anymore. But nobody knows which they are, so they get not deleted.

**Comment by mlitwiniuk** [comment]
Even though you've already figured this out (once again sorry for not answering earlier), but still for future visitors - yes, Lit has implemented "hits count", that saves number of request for every localization key. It's saved in redis, to it's not possible to scope by it for now (but there is PR that implements it: #147  )
