### ISSUE TITLE
Rails 6.1 Update

### ISSUE THREAD

**Issue by bkroeker** [prograils/lit#159]
LIT does not work with Rails 6.1.  ActionView has changed how its `translate` method works, which breaks setting translation defaults in LIT.

As a temporary stopgap, I've monkeypatched the old Rails 6.0 `translate` method into our 6.1 app.

**Comment by pnikrat** [comment]
Looks like Rails team completely broke the possibility of passing default string value in Rails 6.1.. I guess we have to wait for that to be fixed, there is an open merge request in rails repo currently: https://github.com/rails/rails/pull/40691 However it seems that it does not get much attention, it missed two release points (6.1.2 and 6.1.3). Let's hope for it to be merged for next release. For now the only solution is either what you did or wait on Rails 6.0

**Comment by pnikrat** [comment]
Hey, it should work with Rails 6.1.4. Haven't tested it yet but it looks like that issue was merged and released

**Comment by pnikrat** [comment]
Lit release 1.1.5 now works with Rails 6.1 (and updates default values properly after Rails team changed their translate methods)
