### ISSUE TITLE
Lit genenator doesn't work with Ruby 2.3.5 and Rails 4.2.11.3

### ISSUE THREAD

**Issue by jcserracampos** [prograils/lit#179]
After installing lit to my Ruby 2.3.5 and Rails 4.2.11.3 I can't run use rails commands like `rails s` and `rails g lit:install`.

Trace
```
/home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/lit-1.1.4/lib/lit/railtie.rb:6:in `block in <class:Railtie>': uninitialized constant ActiveSupport::Reloader (NameError)
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.11.3/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.11.3/lib/rails/initializable.rb:30:in `run'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.11.3/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:347:in `call'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.11.3/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.11.3/lib/rails/application.rb:352:in `initialize!'
        from /home/jcampos/Projects/bioritmo/Smart-Site/config/environment.rb:5:in `<top (required)>'
        from /home/jcampos/Projects/bioritmo/Smart-Site/config.ru:3:in `block in <main>'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-1.6.12/lib/rack/builder.rb:55:in `instance_eval'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-1.6.12/lib/rack/builder.rb:55:in `initialize'
        from /home/jcampos/Projects/bioritmo/Smart-Site/config.ru:in `new'
        from /home/jcampos/Projects/bioritmo/Smart-Site/config.ru:in `<main>'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-1.6.12/lib/rack/builder.rb:49:in `eval'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-1.6.12/lib/rack/builder.rb:49:in `new_from_string'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-1.6.12/lib/rack/builder.rb:40:in `parse_file'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-1.6.12/lib/rack/server.rb:300:in `build_app_and_options_from_config'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-1.6.12/lib/rack/server.rb:209:in `app'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.11.3/lib/rails/commands/server.rb:61:in `app'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rack-1.6.12/lib/rack/server.rb:337:in `wrapped_app'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.11.3/lib/rails/commands/server.rb:139:in `log_to_stdout'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.11.3/lib/rails/commands/server.rb:78:in `start'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.11.3/lib/rails/commands/commands_tasks.rb:80:in `block in server'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.11.3/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.11.3/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.11.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.11.3/lib/rails/commands.rb:17:in `<top (required)>'
        from /home/jcampos/Projects/bioritmo/Smart-Site/bin/rails:8:in `require'
        from /home/jcampos/Projects/bioritmo/Smart-Site/bin/rails:8:in `<top (required)>'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /home/jcampos/.rbenv/versions/2.3.5/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /home/jcampos/Projects/bioritmo/Smart-Site/bin/spring:16:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
```

My gemfile.lock

<details>
<summary>Gemfile.lock</summary>
<blockquote>
GIT
  remote: https://github.com/bioritmo/geoip2.git
  revision: 643355cdcd733fe1dec75515b5d2b42c84958693
  specs:
    geoip2 (0.0.2)
      activesupport
      faraday
      faraday_middleware
      rash
      typhoeus

GIT
  remote: https://github.com/bioritmo/react-rails.git
  revision: 06562772913954d951e9818d493545c9e809c412
  specs:
    react-rails (2.6.1)
      babel-transpiler (>= 0.7.0)
      connection_pool
      execjs
      railties (>= 3.2)
      tilt

GIT
  remote: https://github.com/bioritmo/wet-health_endpoint.git
  revision: d624c9b3f7b20c36c6864124d9f8c1602276e5bd
  specs:
    wet-health_endpoint (0.2.1)

GIT
  remote: https://105d52ee4627772e650ea48e6b12efba76b27aaa:x-oauth-basic@github.com/bioritmo/bioauth-client.git
  revision: 6227d81eab120915eb6b4ba4095bdf6695a76848
  tag: 0.2.1
  specs:
    bioauth_client (0.2.1)
      jwt
      rails (> 3)

GIT
  remote: https://105d52ee4627772e650ea48e6b12efba76b27aaa:x-oauth-basic@github.com/bioritmo/biogenico.git
  revision: 926a2cb87d7d17d520d8e004970a8ba1ecfe05b2
  tag: 1.0.15
  specs:
    biogenico (1.0.15)
      certifi
      inifile
      nps_sdk (~> 1.2.0)

GEM
  remote: https://rubygems.org/
  specs:
    aasm (4.11.1)
    actionmailer (4.2.11.3)
      actionpack (= 4.2.11.3)
      actionview (= 4.2.11.3)
      activejob (= 4.2.11.3)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.11.3)
      actionview (= 4.2.11.3)
      activesupport (= 4.2.11.3)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.11.3)
      activesupport (= 4.2.11.3)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    active_model-errors_details (1.3.1)
      activemodel (>= 3.2.13, < 5.0.0)
      activesupport
    active_model_serializers (0.10.12)
      actionpack (>= 4.1, < 6.2)
      activemodel (>= 4.1, < 6.2)
      case_transform (>= 0.2)
      jsonapi-renderer (>= 0.1.1.beta1, < 0.3)
    activejob (4.2.11.3)
      activesupport (= 4.2.11.3)
      globalid (>= 0.3.0)
    activemodel (4.2.11.3)
      activesupport (= 4.2.11.3)
      builder (~> 3.1)
    activerecord (4.2.11.3)
      activemodel (= 4.2.11.3)
      activesupport (= 4.2.11.3)
      arel (~> 6.0)
    activesupport (4.2.11.3)
      i18n (~> 0.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    acts_as_list (0.9.19)
      activerecord (>= 3.0)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    administrate (0.2.2)
      autoprefixer-rails (~> 6.0)
      datetime_picker_rails (~> 0.0.7)
      jquery-rails (~> 4.0)
      kaminari (~> 0.16)
      momentjs-rails (~> 2.8)
      neat (~> 1.1)
      normalize-rails (~> 3.0)
      rails (~> 4.2)
      sass-rails (~> 5.0)
      selectize-rails (~> 0.6)
    administrate-field-image (1.1.0)
      administrate (>= 0.2.0.rc1)
    akami (1.3.1)
      gyoku (>= 0.4.0)
      nokogiri
    ancestry (3.2.1)
      activerecord (>= 4.2.0)
    appsignal (2.6.1)
      rack
    arel (6.0.4)
    autoprefixer-rails (6.7.7.2)
      execjs
    awesome_print (1.9.2)
    aws-eventstream (1.1.1)
    aws-sdk (2.11.632)
      aws-sdk-resources (= 2.11.632)
    aws-sdk-core (2.11.632)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sdk-resources (2.11.632)
      aws-sdk-core (= 2.11.632)
    aws-sigv4 (1.2.3)
      aws-eventstream (~> 1, >= 1.0.2)
    babel-source (5.8.35)
    babel-transpiler (0.7.0)
      babel-source (>= 4.0, < 6)
      execjs (~> 2.0)
    bcrypt (3.1.16)
    better_errors (2.1.1)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
      rack (>= 0.9.0)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.7)
      autoprefixer-rails (>= 5.2.1)
      sass (>= 3.3.4)
    bootstrap-tagsinput-rails (0.4.2.1)
      railties (>= 3.1)
    bourbon (7.0.0)
      thor (~> 1.0)
    builder (3.2.4)
    bullet (5.7.5)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.11.0)
    byebug (11.0.1)
    cancancan (1.17.0)
    capybara (2.18.0)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (>= 2.0, < 4.0)
    case_transform (0.2)
      activesupport
    certifi (2018.01.18)
    cliver (0.3.2)
    coderay (1.1.3)
    coffee-rails (4.2.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.2.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.1.9)
    connection_pool (2.2.5)
    crack (0.4.5)
      rexml
    crass (1.0.6)
    dalli (2.7.11)
    database_cleaner (1.99.0)
    date_validator (0.9.0)
      activemodel
      activesupport
    datetime_picker_rails (0.0.7)
      momentjs-rails (>= 2.8.1)
    debug_inspector (1.1.0)
    devise (3.5.6)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    diff-lcs (1.4.4)
    docile (1.3.5)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.7.6)
    dotenv-rails (2.7.6)
      dotenv (= 2.7.6)
      railties (>= 3.2)
    draper (2.1.0)
      actionpack (>= 3.0)
      activemodel (>= 3.0)
      activesupport (>= 3.0)
      request_store (~> 1.0)
    elasticsearch (7.4.0)
      elasticsearch-api (= 7.4.0)
      elasticsearch-transport (= 7.4.0)
    elasticsearch-api (7.4.0)
      multi_json
    elasticsearch-transport (7.4.0)
      faraday
      multi_json
    emoji_flag (0.1.1)
    enumerate_it (1.4.0)
      activesupport (>= 3.0.0)
    enumerize (1.1.1)
      activesupport (>= 3.2)
    envyable (1.0.0)
    erubis (2.7.0)
    ethon (0.14.0)
      ffi (>= 1.15.0)
    execjs (2.8.1)
    factory_girl (4.7.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.7.0)
      factory_girl (~> 4.7.0)
      railties (>= 3.0.0)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    faraday_middleware (0.10.0)
      faraday (>= 0.7.4, < 0.10)
    ffaker (2.6.0)
    ffi (1.15.1)
    file_validators (2.1.0)
      activemodel (>= 3.0)
      mime-types (>= 1.0)
    font-awesome-rails (4.7.0.2)
      railties (>= 3.2, < 5.2)
    geokit (1.13.1)
    geokit-rails (2.3.2)
      geokit (~> 1.5)
      rails (>= 3.0)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    gretel (3.0.9)
      rails (>= 3.1.0)
    gyoku (1.3.1)
      builder (>= 2.1.2)
    hashdiff (1.0.1)
    hashie (2.0.5)
    honeybadger (4.5.5)
    httmultiparty (0.3.16)
      httparty (>= 0.7.3)
      mimemagic
      multipart-post
    http-cookie (1.0.4)
      domain_name (~> 0.5)
    httparty (0.15.7)
      multi_xml (>= 0.5.2)
    httpclient (2.7.2)
    httpi (2.4.5)
      rack
      socksify
    i18n (0.9.5)
      concurrent-ruby (~> 1.0)
    i18n-js (3.0.8)
      i18n (>= 0.6.6, < 2)
    inifile (3.0.0)
    invisible_captcha (0.11.0)
      rails (>= 3.2.0)
    jasmine (2.8.0)
      jasmine-core (>= 2.8.0, < 3.0.0)
      phantomjs
      rack (>= 1.2.1)
      rake
    jasmine-core (2.99.2)
    jbuilder (2.9.1)
      activesupport (>= 4.2.0)
    jmespath (1.4.0)
    jquery-rails (4.4.0)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (6.0.1)
      railties (>= 3.2.16)
    json (1.8.6)
    json-api-vanilla (1.0.1)
    jsonapi-renderer (0.2.2)
    jwt (1.5.6)
    kaminari (0.17.0)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    kgio (2.11.4)
    lit (1.1.4)
      coffee-rails
      emoji_flag
      jquery-rails
      rails (>= 4.2.0)
      sass-rails
    loofah (2.10.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    method_source (1.0.0)
    mime-types (2.99.3)
    mimemagic (0.3.10)
      nokogiri (~> 1)
      rake
    mini_magick (4.7.0)
    mini_mime (1.1.0)
    mini_portile2 (2.4.0)
    minitest (5.14.4)
    momentjs-rails (2.20.1)
      railties (>= 3.1)
    multi_json (1.15.0)
    multi_xml (0.6.0)
    multipart-post (2.1.1)
    mysql2 (0.3.21)
    neat (1.7.4)
      bourbon (>= 4.0)
      sass (>= 3.3)
    netrc (0.11.0)
    nokogiri (1.10.10)
      mini_portile2 (~> 2.4.0)
    nori (2.6.0)
    normalize-rails (3.0.3)
    nps_sdk (1.2.0)
      certifi (~> 2018.1, >= 2018.01.18)
      httpclient (~> 2.7.1)
      inifile (~> 3.0)
      savon (~> 2.11)
    oauth2 (1.4.7)
      faraday (>= 0.8, < 2.0)
      jwt (>= 1.0, < 3.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    omniauth (1.4.2)
      hashie (>= 1.2, < 4)
      rack (>= 1.0, < 3)
    omniauth-facebook (4.0.0)
      omniauth-oauth2 (~> 1.2)
    omniauth-google-oauth2 (0.5.2)
      jwt (~> 1.5)
      multi_json (~> 1.3)
      omniauth (>= 1.1.1)
      omniauth-oauth2 (>= 1.3.1)
    omniauth-oauth2 (1.5.0)
      oauth2 (~> 1.1)
      omniauth (~> 1.2)
    orm_adapter (0.5.0)
    phantomjs (2.1.1.0)
    poltergeist (1.18.0)
      capybara (>= 2.1, < 4)
      cliver (~> 0.3.1)
      websocket-driver (>= 0.2.0)
    pry (0.14.1)
      coderay (~> 1.1)
      method_source (~> 1.0)
    pry-byebug (3.7.0)
      byebug (~> 11.0)
      pry (~> 0.10)
    pry-meta (0.0.10)
      awesome_print
      pry
      pry-byebug
      pry-remote
    pry-remote (0.1.8)
      pry (~> 0.9)
      slop (~> 3.0)
    public_suffix (4.0.6)
    quiet_assets (1.1.0)
      railties (>= 3.1, < 5.0)
    rack (1.6.12)
    rack-protection (1.5.5)
      rack
    rack-proxy (0.7.0)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.11.3)
      actionmailer (= 4.2.11.3)
      actionpack (= 4.2.11.3)
      actionview (= 4.2.11.3)
      activejob (= 4.2.11.3)
      activemodel (= 4.2.11.3)
      activerecord (= 4.2.11.3)
      activesupport (= 4.2.11.3)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.11.3)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.4)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.9)
      activesupport (>= 4.2.0, < 5.0)
      nokogiri (~> 1.6)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    rails-jquery-autocomplete (1.0.5)
      rails (>= 3.2)
    rails_autolink (1.1.6)
      rails (> 3.1)
    railties (4.2.11.3)
      actionpack (= 4.2.11.3)
      activesupport (= 4.2.11.3)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    raindrops (0.19.2)
    rake (13.0.3)
    rash (0.4.0)
      hashie (~> 2.0.0)
    rb-fsevent (0.11.0)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rb-readline (0.5.5)
    rdoc (4.3.0)
    redis (3.3.1)
    refile (0.6.2)
      mime-types
      rest-client (~> 1.8)
      sinatra (~> 1.4.5)
    refile-s3 (0.2.0)
      aws-sdk (~> 2.0)
      refile (~> 0.6.0)
    request_store (1.5.0)
      rack (>= 1.4)
    responders (2.4.1)
      actionpack (>= 4.2.0, < 6.0)
      railties (>= 4.2.0, < 6.0)
    rest-client (1.8.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.7)
    rexml (3.2.5)
    route_translator (4.3.0)
      actionpack (>= 3.2, < 5.0)
      activesupport (>= 3.2, < 5.0)
    rspec-collection_matchers (1.2.0)
      rspec-expectations (>= 2.99.0.beta1)
    rspec-core (3.8.2)
      rspec-support (~> 3.8.0)
    rspec-expectations (3.8.6)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-mocks (3.8.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-rails (3.8.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.8.0)
      rspec-expectations (~> 3.8.0)
      rspec-mocks (~> 3.8.0)
      rspec-support (~> 3.8.0)
    rspec-support (3.8.3)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.0.7)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    savon (2.12.1)
      akami (~> 1.2)
      builder (>= 2.1.2)
      gyoku (~> 1.2)
      httpi (~> 2.3)
      nokogiri (>= 1.8.1)
      nori (~> 2.4)
      wasabi (~> 3.4)
    sdoc (0.4.2)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    searchkick (2.3.0)
      activemodel (>= 4.1)
      elasticsearch (>= 1)
      hashie
    selectize-rails (0.12.6)
    shoulda-matchers (4.0.1)
      activesupport (>= 4.2.0)
    simplecov (0.17.1)
      docile (~> 1.1)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.2)
    sinatra (1.4.8)
      rack (~> 1.5)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    sitemap_generator (6.0.1)
      builder (~> 3.0)
    slop (3.6.0)
    socksify (1.7.1)
    spring (2.0.2)
      activesupport (>= 4.2)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-es6 (0.9.2)
      babel-source (>= 5.8.11)
      babel-transpiler
      sprockets (>= 3.0.0)
    sprockets-rails (3.2.2)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    thor (1.1.0)
    thread_safe (0.3.6)
    tilt (2.0.10)
    timecop (0.9.4)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    tzinfo (1.2.9)
      thread_safe (~> 0.1)
    uglifier (4.2.0)
      execjs (>= 0.3.0, < 3)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.7)
    unicorn (5.5.1)
      kgio (~> 2.6)
      raindrops (~> 0.7)
    uniform_notifier (1.11.0)
    valid_url (0.0.4)
      addressable
      rails
    vcr (3.0.3)
    warden (1.2.7)
      rack (>= 1.0)
    wasabi (3.6.1)
      addressable
      httpi (~> 2.0)
      nokogiri (>= 1.4.2)
    webmock (3.0.1)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff
    webpacker (4.2.2)
      activesupport (>= 4.2)
      rack-proxy (>= 0.6.1)
      railties (>= 4.2)
    websocket-driver (0.7.4)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    x-editable-rails (1.5.5.1)
      railties
    xpath (3.2.0)
      nokogiri (~> 1.8)

PLATFORMS
  ruby

DEPENDENCIES
  aasm (= 4.11.1)
  active_model-errors_details (= 1.3.1)
  active_model_serializers (~> 0.10.0)
  acts_as_list
  administrate (~> 0.2.1)
  administrate-field-image
  ancestry
  appsignal (= 2.6.1)
  better_errors (= 2.1.1)
  binding_of_caller (= 0.7.2)
  bioauth_client!
  biogenico (= 1.0.15)!
  bootstrap-sass (~> 3.3.5)
  bootstrap-tagsinput-rails (= 0.4.2.1)
  bourbon
  bullet (= 5.7.5)
  byebug
  cancancan (~> 1.10)
  capybara (= 2.18.0)
  coffee-rails (= 4.2.1)
  dalli
  database_cleaner
  date_validator (= 0.9.0)
  devise (= 3.5.6)
  dotenv-rails
  draper
  enumerate_it (= 1.4.0)
  enumerize (= 1.1.1)
  envyable (= 1.0.0)
  factory_girl_rails (~> 4.7.0)
  faraday (= 0.9.2)
  faraday_middleware (= 0.10.0)
  ffaker (= 2.6.0)
  file_validators (= 2.1.0)
  font-awesome-rails (= 4.7.0.2)
  geoip2!
  geokit
  geokit-rails
  gretel
  honeybadger (< 4.5.6)
  httmultiparty (= 0.3.16)
  httparty (= 0.15.7)
  i18n-js (= 3.0.8)
  invisible_captcha (= 0.11.0)
  jasmine (= 2.8.0)
  jbuilder (~> 2.0)
  jquery-rails
  jquery-ui-rails
  json-api-vanilla (= 1.0.1)
  kaminari
  lit
  mimemagic (= 0.3.10)
  mini_magick (= 4.7.0)
  mysql2 (~> 0.3.13)
  nokogiri (~> 1.10.1)
  omniauth (= 1.4.2)
  omniauth-facebook (= 4.0.0)
  omniauth-google-oauth2 (= 0.5.2)
  poltergeist (= 1.18)
  pry-meta
  quiet_assets (= 1.1.0)
  rack (= 1.6.12)
  rails (= 4.2.11.3)
  rails-jquery-autocomplete
  rails_autolink (= 1.1.6)
  rb-readline (~> 0.5.0)
  react-rails!
  redis (= 3.3.1)
  refile
  refile-s3
  route_translator (= 4.3.0)
  rspec-collection_matchers
  rspec-rails (= 3.8.2)
  sass-rails (~> 5.0.4)
  sdoc (~> 0.4.0)
  searchkick (= 2.3.0)
  shoulda-matchers
  simplecov
  sitemap_generator (= 6.0.1)
  spring (= 2.0.2)
  sprockets (>= 3.0.0)
  sprockets-es6 (~> 0.9.0)
  timecop
  uglifier (>= 4.1.10)
  unicorn (= 5.5.1)
  valid_url
  vcr (= 3.0.3)
  webmock (= 3.0.1)
  webpacker (~> 4.2.2)
  wet-health_endpoint!
  x-editable-rails (= 1.5.5.1)

BUNDLED WITH
   1.17.3
</blockquote>

</details>

**Comment by mlitwiniuk** [comment]
@jcserracampos Rails 4.x is no longer supported, we're only focusing on supported Rails versions, so 5.2, 6.0 and 6.1 now.
