### ISSUE TITLE
Support for pluralization

### ISSUE THREAD

**Issue by voondo** [prograils/lit#47]
It seems that lit doesn't support pluralization as described here : http://guides.rubyonrails.org/i18n.html#pluralization

Any plan to add this feature ?

**Comment by fero46** [comment]
The Problem I see is that you include I18n::Backend::Simple::Implementation that didn't support pluralization. To Support this feature you had to include 
```ruby
  I18n::Backend::Simple.include(I18n::Backend::Pluralization)
```
and extend the translate method in your implementation

```ruby
count, default = options.values_at(:count, :default)
# some code
 entry = pluralize(locale, entry, count) if count
```
I didn't test this. But it should work, maybe when I have time, i will make a pull request.

**Comment by mlitwiniuk** [comment]
@fero46 @voondo basically you should import `I18n::Backend::Pluralization` into `I18n::Backend` by your self - by default it is not supported by rails (rails-i18n imports it for you - https://github.com/svenfuchs/rails-i18n/blob/master/lib/rails_i18n/railtie.rb#L30 ). So I don't know if this is a bug - this may thou require more information in Wiki or Readme file.
What's your opinion on that?

**Comment by Silex** [comment]
I think this issue should be reopened... pluralization is an important i18n feature.
