### ISSUE TITLE
lit without redis?

### ISSUE THREAD

**Issue by oneiros** [prograils/lit#56]
lit looks awesome. So awesome, that I would like to try it for a project I am working on. But I do not want to introduce redis into this project. At least not at this point.

I had a quick look around and I see two possible approaches for me:

1.) Write a dummy adapter that does not really cache, so the DB has to be queried every time. Not ideal from a performance standpoint but I guess it should be no worse than using the i18n active_record backend.

2.) Do not use lit's i18n backend and simply export yml files (maybe periodically using a cron job).

What would you recommend?

Thanks a in advance and keep up the good work!

**Comment by mlitwiniuk** [comment]
Hi, first of all thanks :)
Basically it all depends on your use case. You could go with yml export on every deploy - but then you should translate your app in development or staging environment.
Writing dummy db adapter is possible as well, it will introduce extra load, but as long, as you don't have many translations on single page and / or no high load, I would go with it.
