### ISSUE TITLE
Translation values are overwritten with nil when present in DB and not redis

### ISSUE THREAD

**Issue by vincentvanbush** [prograils/lit#79]
Translations are fetched into the database and then pre-loaded into Redis. If Redis crashes and the developer deletes default values from `I18n.t` calls, counting on them being present in SQL anyway, the cache erroneously causes translation queries to return `translation missing` and overwrite their database records. (@mlitwiniuk please make a clarification if this is not specific enough)

**Comment by mlitwiniuk** [comment]
existing db records should not be ever deleted IMO (unless deleted via lit). If `default` param of `I18n.t` call changes, it might be good to change `default_value` of db record, but not `translated_value`
