### ISSUE TITLE
Sync between servers

### ISSUE THREAD

**Issue by johansmitsnl** [prograils/lit#85]
I'm looking for a solution to translate our rails apps. 
We have a development (rails production env) environment where we want to have users to translate the environment. 
Is there a way to retrieve / sync the keys to a developer so that the changes in the translations can be committed?

**Comment by mlitwiniuk** [comment]
@johansmitsnl hi, sorry for not spotting this later. I assume, that you've already solved your problem. If not, this gem might be helpful, as sync feature is already implemented. I'll try to record screencast showing how to use it.

**Comment by johansmitsnl** [comment]
Would love to see the screencast if you have the time.
The project is not very active at the moment but it will pick up soon again for more languages. So would love it to see a screencast.
