### ISSUE TITLE
Release a version which is compatible with Rails 5

### ISSUE THREAD

**Issue by lichtamberg** [prograils/lit#92]
Could you maybe release a new version? The last is from 2016?

**Comment by inkkin** [comment]
Hi @lichtamberg 
We've changed a lot in master, but you're right, it's time for a release. 
We'll try to do that next week!

**Comment by lichtamberg** [comment]
Thanks! :)

Yeah, won't get better in the future xD

**Comment by RaphaelAudet** [comment]
Hi, this project sounds great, any plans on a release for rails 5 ?

**Comment by klapperkopp** [comment]
Is it next week yet? I'd also really like to use this one in rails 5. :)

**Comment by mlitwiniuk** [comment]
@klapperkopp @RaphaelAudet version in master already works well with Rails5, you can lock it to version to be sure it won't change. In fact I might release it today, I'd love your feedback about new features.

**Comment by Extazystas** [comment]
@mlitwiniuk I'm getting the errors like 
```
The asset "lit/famfamfam_flags/ak.png" is not present in the asset pipeline.
```
After adding lit/famfamfam_flags/*  to assets precompile on Rails 5. Do you know how to fix that?

**Comment by zhisme** [comment]
@Extazystas It's fixed with the last PR approved, you can check. I tested it in my application and it works fine. version 0.3.0 of this gem

**Comment by mlitwiniuk** [comment]
@zhisme @Extazystas just bear with me for a moment here, there are some issues with Rails 5.1.4, I'm fixing them now. Version 0.3.0 will be released today as a gem
