### ISSUE TITLE
Attempting to generate a URL from non-sanitized request parameters

### ISSUE THREAD

**Issue by Chris24680** [prograils/lit#94]
Hi I've just tried to install lit in my project, but I'm getting the error 

`ArgumentError at /localization_keys`

`Attempting to generate a URL from non-sanitized request parameters! An attacker can inject malicious data into the generated URL, such as changing the host. Whitelist and sanitize passed parameters to be secure.`

When trying to view the localisation keys, I'm using Rails 5.0.6, Ruby 2.3.2

**Comment by mlitwiniuk** [comment]
@Chris24680 I'll look into this later today. I'm not sure what's happening, as I've just successfully tested that on Rails 4.2 and 5.1.

**Comment by mlitwiniuk** [comment]
@Chris24680 are you sure you're using version 0.3.0?

**Comment by Chris24680** [comment]
Ah sorry, I didn't specify a version in my gemfile and it installed 0.2.4, I'm not sure why it didn't install 0.3.0, but after specifying the version it's working now, thanks.

**Comment by mlitwiniuk** [comment]
@Chris24680 version 0.3.0 was released 30 minutes ago - that might be a reason ;)
