### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by Silex** [prograils/lit#98]
Hello,

FYI I'm fixing the tests at https://github.com/svenfuchs/i18n/pull/417

I'm not sure what would need to be changed in here to repair the tests for rails 5.1, maybe force the i18n version to be the latest (once my patch is accepted and a release is made)? That or check for Rails 5.1 in the tests and monkey patch `assert_nothing_raised`?

**Comment by pnikrat** [comment]
Tests currently all pass locally under Rails 5.2, 6.0 and 6.1. Travis builds are turned off though because of some CI problems
